// ============================================================
//  Portfolio Data — edit this file to update projects/tools/designs
// ============================================================

const PROJECTS = [
  {
    slug: "chessist",
    title: "Chessist",
    description: "Chrome extension that runs Stockfish inside Chess.com. Live eval bar, best move arrows, and auto-move, all in the browser.",
    tags: ["JavaScript", "Chrome Extension", "Chess Engine"],
    link: "https://github.com/imluri/Chessist",
    image: "https://raw.githubusercontent.com/imluri/Chessist/main/logo.png",
    imageAlt: "Chessist Logo",
    details: {
      year: "2026",
      status: "Active",
      summary: "Chessist runs a full Stockfish WASM engine inside Chess.com. Live eval bar, best-move arrow overlays, and optional auto-move, all without leaving the browser.",
      highlights: [
        "Stockfish running entirely in the browser via WebAssembly, no server needed",
        "Live eval bar that updates move-by-move",
        "Best move arrow overlays drawn directly on the Chess.com board",
        "Auto-move with configurable depth and time controls",
        "Fully client-side, no external dependencies",
      ],
      tech: ["JavaScript", "WebAssembly", "Chrome Extensions API", "Stockfish"],
    },
  },
  {
    slug: "apktoolkit",
    title: "APK Toolkit",
    description: "Batch and Python scripts for modding Android APKs. Wraps apktool, smali, and the signer into a step-by-step pipeline you can actually follow.",
    tags: ["Batchfile", "Python", "Android"],
    link: "https://github.com/imluri/apktoolkit",
    image: "https://raw.githubusercontent.com/imluri/apktoolkit/main/logo.png",
    imageAlt: "APK Toolkit Logo",
    details: {
      year: "2026",
      status: "Active",
      summary: "APK Toolkit is a Windows batch + Python workflow that wraps apktool, baksmali, smali, and uber-apk-signer into a numbered pipeline: extract, decompile, patch, build, sign, install.",
      highlights: [
        "Numbered batch scripts for each stage so you always know where you are",
        "Python scripts for patching smali bytecode and AndroidManifest.xml",
        "Ships with apktool, baksmali, smali, and uber-apk-signer bundled in",
        "One-command full flow script if you just want to run the whole thing",
        "Built to be repeatable, easy to drop into any mod workflow",
      ],
      tech: ["Batchfile", "Python", "apktool", "smali / baksmali", "uber-apk-signer"],
    },
  },
  {
    slug: "iyai",
    title: "IYAI",
    description: "Lua plugin for Infinite Yield that adds a full AI assistant. It can explore the game tree, run Lua, search the web, and fire IY commands, all from a chat UI.",
    tags: ["Lua", "AI", "Plugin"],
    link: "https://github.com/imluri/IYAI",
    image: "https://raw.githubusercontent.com/imluri/IYAI/main/logo.png",
    imageAlt: "IYAI Logo",
    details: {
      year: "2026",
      status: "Active",
      summary: "IYAI is a Lua plugin for the Infinite Yield Roblox admin script that wires in a full AI assistant. It can browse the instance tree, read and set properties, write and run Lua, search the web, and fire IY commands, all from a chat UI.",
      highlights: [
        "Full AI chat loop with tool calls, reasoning, and streamed responses",
        "Browse the Roblox instance tree and read/set properties on any object",
        "Write, edit, and execute Lua directly from the plugin",
        "Works with OpenRouter, Mistral, Groq, Google AI Studio, Pollinations, HuggingFace, and Ollama",
        "Live model picker that pulls available models from whichever provider you pick",
        "Rate-limit retry, inline error display, stop button, and full session history",
        "GUI parented to gethui so the game doesn't detect it",
        "Auto-updates on every run by pulling the latest version from GitHub",
      ],
      tech: ["Lua", "Roblox API", "OpenRouter", "Groq", "Google AI Studio", "DuckDuckGo Search"],
    },
  },
  {
    slug: "lami",
    title: "Lami",
    description: "AI chatbot I built using MCP architecture. Hooks into live data, automates tasks, and actually understands context across a conversation.",
    tags: ["Python", "Flask", "AI", "MCP"],
    link: "https://lami.up.railway.app/",
    image: "assets/lami-web.png",
    imageAlt: "Lami",
    fullscreen: true,
    details: {
      year: "2025",
      status: "Active",
      summary: "Lami is an AI chatbot built on MCP (Model Context Protocol). It pulls in live data, automates tasks on command, and keeps context across the whole conversation.",
      highlights: [
        "MCP architecture so the AI can actually act on things, not just talk about them",
        "Hooks into real-time data sources and runs analysis on the fly",
        "Natural language task automation, just tell it what to do",
        "Python/Flask backend with a clean responsive frontend",
        "Deployed on Railway with persistent session management",
      ],
      tech: ["Python", "Flask", "MCP", "NLP", "HTML/CSS", "Real-Time Data"],
    },
  },
  {
    slug: "sedapsnaps",
    title: "SedapSnaps",
    description: "Food discovery PWA with AI recommendations, full offline support, and push notifications. Scored 95 on Lighthouse and got 60% higher mobile engagement.",
    tags: ["PWA", "JavaScript", "AI"],
    link: "https://sedapsnaps.com",
    image: "assets/sedapsnaps.png",
    imageAlt: "SedapSnaps",
    fullscreen: true,
    details: {
      year: "2024",
      status: "Active",
      summary: "SedapSnaps is a food discovery PWA with AI recommendations. Works fully offline, sends push notifications, and scored 95 on Lighthouse with 60% higher mobile engagement.",
      highlights: [
        "AI recommendations that actually match what the user wants",
        "Full offline mode with service worker and local caching",
        "Push notifications for new food discoveries",
        "95 Lighthouse PWA score across performance, accessibility, and best practices",
        "60% higher mobile engagement over the baseline",
      ],
      tech: ["JavaScript", "PWA", "Service Workers", "Push API", "AI Recommendations"],
    },
  },
  {
    slug: "cibot",
    title: "AI Environmental Reporting Bot",
    description: "Chatbot where citizens can report environmental issues via chat, attach photos, and it generates a structured report for the relevant government department.",
    tags: ["Python", "NLP", "Image Analysis", "AI"],
    link: "https://cibot.my",
    image: "assets/cibot.png",
    imageAlt: "CiBot",
    fullscreen: true,
    details: {
      year: "2025",
      status: "Active",
      summary: "CiBot is an AI chatbot I built during my internship. Citizens can report potholes, flooding, illegal dumping, whatever, just send a message and a photo and it generates a proper incident report for the government.",
      highlights: [
        "Chat interface so anyone can report an issue without filling out a form",
        "Analyses attached images to figure out what's actually being reported",
        "Generates structured, government-ready incident reports automatically",
        "NLP intent classification routes each report to the right department",
        "Built and deployed during my AI Engineering internship",
      ],
      tech: ["Python", "NLP", "Image Analysis", "Report Generation", "Government Integration"],
    },
  },
];

const TOOLS = [
  {
    title: "Network Utilities",
    description: "Local scripts for testing connectivity, diagnosing network issues, and measuring performance.",
    tags: ["Networking", "Tools", "Diagnostics"],
    icon: "mdi:server-network",
    link: null,
  },
  {
    title: "Performance Tools",
    description: "Scripts for measuring latency and response time. Mostly built for checking if my changes actually made things faster.",
    tags: ["Performance", "Monitoring", "Analysis"],
    icon: "mdi:speedometer",
    link: null,
  },
  {
    title: "3D Experiments",
    description: "Playing around with interactive 3D in the browser. Mostly visual prototypes and rendering tests.",
    tags: ["3D", "Visualization", "Interactive"],
    icon: "mdi:cube-scan",
    link: null,
  },
  {
    title: "Game Prototypes",
    description: "Half-finished game ideas and browser experiments. Some get finished, most don't.",
    tags: ["Games", "Prototype", "Browser"],
    icon: "mdi:gamepad-square",
    link: null,
  },
];

const DESIGNS = [];

// Web design concepts — shown via iframe on the project detail page
const DESIGN_PROJECTS = [
  {
    slug: "nke",
    title: "Nasi Kandar Express",
    description: "Mamak restaurant website concept. Bright colours, bold type, warm layout. Built with plain HTML and CSS.",
    tags: ["UI/UX", "HTML", "CSS"],
    link: null,
    image: "https://raw.githubusercontent.com/imluri/imluri.github.io/main/assets/NKE_web.png",
    imageAlt: "Nasi Kandar Express preview",
    fullscreen: true,
    designSrc: "designs/NKE.html",
    details: {
      year: "2024",
      status: "Design",
      summary: "Concept website for a mamak restaurant chain. Bright colours, bold text, warm feel. Built with plain HTML and CSS.",
      highlights: [
        "Warm, high-contrast colours that fit the mamak vibe",
        "Bold hero section with a clear CTA",
        "Responsive layout in pure HTML and CSS",
        "Menu section with a card-based food display",
      ],
      tech: ["HTML", "CSS"],
    },
  },
  {
    slug: "browniemunch",
    title: "BROWNIEMUNCH",
    description: "Bakery website concept with warm chocolate tones, product showcase, and a cozy layout that makes you want to order something.",
    tags: ["UI/UX", "HTML", "CSS"],
    link: null,
    image: "https://raw.githubusercontent.com/imluri/imluri.github.io/main/assets/BROWNIEMUNCH_web.png",
    imageAlt: "BROWNIEMUNCH preview",
    fullscreen: true,
    designSrc: "designs/browniemunch.html",
    details: {
      year: "2024",
      status: "Design",
      summary: "Concept website for an artisanal brownie brand. Warm chocolate tones, cozy layout, the kind of site that makes you want to buy something.",
      highlights: [
        "Chocolate and cream colour scheme that fits the brand",
        "Product showcase grid with hover effects",
        "Typography that feels handmade without being hard to read",
        "Fully responsive across mobile and desktop",
      ],
      tech: ["HTML", "CSS"],
    },
  },
  {
    slug: "nexus",
    title: "Nexus.AI",
    description: "Dark sci-fi SaaS landing page concept. Glowing cyan accents, animated typewriter hero, and the kind of vibe that says 'we use AI for everything'.",
    tags: ["UI/UX", "HTML", "Tailwind"],
    link: null,
    image: null,
    icon: "mdi:web",
    imageAlt: "Nexus.AI preview",
    designSrc: "designs/nexus.html",
    details: {
      year: "2024",
      status: "Design",
      summary: "Dark sci-fi SaaS landing page concept for a fictional AI platform. Glowing cyan, animated typewriter hero, the full thing.",
      highlights: [
        "Animated typewriter effect in the hero",
        "Glowing cyan accents on a pure black background",
        "Glassmorphism feature cards with a subtle border glow",
        "Pricing section and CTA that feel intentional",
      ],
      tech: ["HTML", "Tailwind CSS"],
    },
  },
];

// Hobby projects — personal stuff outside work
const HOBBIES = [
  {
    title: "Unity Game Mods & Cheats",
    description: "C# mods for Unity games. Memory patching, internal hooks, overlays, automation. The kind of stuff you can't google.",
    tags: ["C#", "Unity", "Reverse Engineering"],
    icon: "mdi:sword-cross",
    link: null,
  },
  {
    title: "Game Development",
    description: "Personal Unity projects. Some are just mechanics experiments, a few actually got finished.",
    tags: ["C#", "Unity", "Game Dev"],
    icon: "mdi:controller-classic",
    link: null,
  },
  {
    title: "Roblox / Luau Scripting",
    description: "Games and tools built on Roblox. Multiplayer systems, admin scripts, random gameplay stuff.",
    tags: ["Luau", "Roblox", "Games"],
    icon: "mdi:gamepad-variant",
    link: null,
  },
];
