// ============================================================
//  Portfolio Data — edit this file to update projects/tools/designs
// ============================================================

const PROJECTS = [
  {
    slug: "qsm",
    title: "QSM",
    description: "A quantum programming language with Lua-like syntax, compiled down to Qiskit. Write quantum circuits without learning a whole new paradigm.",
    tags: ["Python", "Qiskit", "Quantum Computing"],
    link: "https://github.com/imluri/qsm",
    image: "https://raw.githubusercontent.com/imluri/qsm/main/logo.png",
    imageAlt: "QSM Logo",
    icon: "mdi:atom",
    details: {
      year: "2025",
      status: "Active",
      summary: "QSM is a custom programming language I built that lets you write quantum circuits using Lua-like syntax. It compiles down to Qiskit under the hood, so you get the full power of quantum computing without having to learn Qiskit's API directly.",
      highlights: [
        "Custom parser and compiler written in Python",
        "Supports Hadamard, X, Y, Z, S, T gates, CNOT, SWAP, and multi-controlled Z",
        "Classical control flow: if/while/for loops and variable assignments inside quantum programs",
        "User-defined functions and measurement operations",
        "Includes a full Grover's algorithm example",
        "Designed to make quantum computing accessible without prior Qiskit knowledge",
      ],
      tech: ["Python", "Qiskit", "Custom Parser", "Quantum Gates"],
    },
  },
  {
    slug: "chessist",
    title: "Chessist",
    description: "Desktop app and browser extension for live Stockfish analysis on Chess.com and Lichess. Eval bar, best-move arrows, a screen-capture-invisible overlay, and human-like auto-move.",
    tags: ["Electron", "React", "Chess Engine"],
    link: "https://github.com/imluri/Chessist",
    image: "https://raw.githubusercontent.com/imluri/Chessist/main/logo.png",
    imageAlt: "Chessist Logo",
    details: {
      year: "2026",
      status: "Active",
      summary: "Chessist gives you live Stockfish analysis on Chess.com and Lichess, as both a browser extension and a desktop app. Eval bar, best-move arrow overlays, a transparent overlay that stays invisible to screen capture, and human-like auto-move.",
      highlights: [
        "Works on both Chess.com and Lichess",
        "Live eval bar and best-move arrows that update move-by-move",
        "Transparent overlay that doesn't show up in screen captures",
        "Human-like auto-move with configurable timing",
        "Available as a Chrome extension and an Electron desktop app",
      ],
      tech: ["JavaScript", "Electron", "React", "Vite", "Stockfish"],
    },
  },
  {
    slug: "netpad",
    title: "netpad",
    description: "Turn your phone into a wireless Xbox 360 or DualShock 4 controller for PC games over local Wi-Fi. Up to 4 players, each with a fully customizable on-screen layout.",
    tags: ["Node.js", "WebSocket", "ViGEm"],
    link: "https://github.com/imluri/netpad",
    image: "https://raw.githubusercontent.com/imluri/netpad/main/docs/irl_preview.png",
    imageAlt: "netpad running as a phone controller",
    fullscreen: true,
    icon: "mdi:gamepad-variant",
    details: {
      year: "2026",
      status: "Active",
      summary: "netpad turns any phone into a wireless Xbox (XInput) or PlayStation (DS4) controller for PC games over local Wi-Fi. Up to 4 players at once, each with a fully customizable touch layout, all driven through the ViGEm virtual gamepad bus.",
      highlights: [
        "Each phone connects as an Xbox or PlayStation controller on slots 1–4",
        "Drag-and-resize touch layout editor with presets and import/export",
        "Sticks, d-pad, analog/digital triggers, chord buttons, and the DS4 touchpad",
        "Low-latency WebSocket transport with automatic HTTP fallback",
        "Live monitor and connection latency debug pages",
      ],
      tech: ["Node.js", "WebSocket", "ViGEm Bus", "XInput", "DS4"],
    },
  },
  {
    slug: "unifia",
    title: "Unifia",
    description: "Cross-store multiplayer launcher. Play with friends regardless of which store they bought the game on, over a direct IP connection that bypasses platform lobbies.",
    tags: ["Electron", "React", "Networking"],
    link: "https://github.com/imluri/Unifia",
    icon: "mdi:rocket-launch-outline",
    details: {
      year: "2026",
      status: "Active",
      summary: "Unifia is a cross-store multiplayer game launcher. It lets players on Steam, GOG, Epic, or anywhere else play together over a direct IP connection, bypassing store-locked matchmaking. Free and open source.",
      highlights: [
        "No platform lock-in, scans installed games across stores and treats them uniformly",
        "Direct IP connection: one player hosts a port, others connect by IP:PORT",
        "On-demand module system that fetches loaders like BepInEx from official sources",
        "Game-specific patching (e.g. shared Photon AppId) for cross-store sessions",
        "Version-mismatch detection on connect",
      ],
      tech: ["Electron", "React", "Vite", "Tailwind CSS", "zustand", "Node net"],
    },
  },
  {
    slug: "meshysec",
    title: "MeshySec",
    description: "Chrome extension that exports your Meshy 3D models to GLB right from the viewer. One click, no paywall, all client-side.",
    tags: ["Chrome Extension", "Three.js", "WebGL"],
    link: "https://github.com/imluri/MeshySec",
    webLink: "/model-map",
    image: "https://raw.githubusercontent.com/imluri/MeshySec/main/logo.png",
    imageAlt: "MeshySec Logo",
    details: {
      year: "2026",
      status: "Active",
      summary: "MeshySec adds a GLB export button straight to the Meshy model viewer. Open one of your models, click the button, and the model downloads as a .glb. It reads the model out of the viewer's 3D scene in your browser, so nothing gets uploaded anywhere.",
      highlights: [
        "Adds a one-click GLB button right inside the Meshy viewer",
        "Export with PBR textures (base color, normal, metallic/roughness) or geometry only",
        "Fully client-side: reads the model from the browser's 3D scene, no uploads",
        "Built on React Three Fiber and Three.js, Manifest V3",
        "One-click install script for Windows",
      ],
      tech: ["JavaScript", "React Three Fiber", "Three.js", "WebGL", "Manifest V3"],
    },
  },
  {
    slug: "promptforge",
    title: "PromptForge",
    description: "Fluent LLM request builder for Luau. Chain messages, tools, and completions across providers like OpenRouter, OpenAI, Groq, Mistral, and Ollama.",
    tags: ["Luau", "LLM", "Library"],
    link: "https://github.com/imluri/PromptForge",
    icon: "mdi:anvil",
    details: {
      year: "2026",
      status: "Active",
      summary: "PromptForge is a fluent request builder for working with LLMs from Luau. Chain a provider, model, messages, tools, and parameters with a clean builder API, then send, all across a range of providers behind one interface.",
      highlights: [
        "Fluent builder API: chain provider, model, messages, and params, then :send()",
        "One interface across OpenRouter, OpenAI, Mistral, Groq, Pollinations, HuggingFace, Google, and Ollama",
        "System / user / assistant messages and raw message tables",
        "Tool / function-calling support",
        "Installable via Wally or by dropping in the source",
      ],
      tech: ["Luau", "Wally", "LLM APIs"],
    },
  },
  {
    slug: "bogglesolver",
    title: "Boggle Solver",
    description: "Desktop Boggle solver with OCR grid capture and an auto-play mouse driver. Snip the board, it reads the letters, finds every word, and can drag the mouse through them.",
    tags: ["Python", "OCR", "EasyOCR"],
    link: "https://github.com/imluri/BoggleSolver",
    image: "https://raw.githubusercontent.com/imluri/BoggleSolver/main/screenshot.png",
    imageAlt: "Boggle Solver app screenshot",
    fullscreen: true,
    icon: "mdi:grid",
    details: {
      year: "2026",
      status: "Active",
      summary: "A desktop Boggle solver with OCR grid capture and an auto-play mouse driver for Roblox or any Boggle-style game. Snip your board, EasyOCR reads the letters, a DFS trie search finds every valid word, and it can drive the mouse through each one.",
      highlights: [
        "OCR capture: snip the board with Win+Shift+S and paste, EasyOCR fills the letters",
        "DFS trie solver finds every valid word, sorted by length, with path tracing",
        "Auto-play drags the mouse through every word after a one-time grid calibration",
        "Swappable word lists and grid sizes from 3×3 to 6×6",
        "Frameless dark always-on-top UI with smooth movement for DirectInput games",
      ],
      tech: ["Python", "EasyOCR", "Trie / DFS", "Computer Vision"],
    },
  },
  {
    slug: "apktoolkit",
    title: "APK Toolkit",
    description: "Batch and Python scripts for modding Android APKs. Wraps apktool, smali, and the signer into a step-by-step pipeline you can actually follow.",
    tags: ["Batchfile", "Python", "Android"],
    link: "https://github.com/imluri/apktoolkit",
    image: "https://raw.githubusercontent.com/imluri/apktoolkit/main/logo.png",
    imageAlt: "APK Toolkit Logo",
    details: {
      year: "2026",
      status: "Active",
      summary: "APK Toolkit is a Windows batch + Python workflow that wraps apktool, baksmali, smali, and uber-apk-signer into a numbered pipeline: extract, decompile, patch, build, sign, install.",
      highlights: [
        "Numbered batch scripts for each stage so you always know where you are",
        "Python scripts for patching smali bytecode and AndroidManifest.xml",
        "Ships with apktool, baksmali, smali, and uber-apk-signer bundled in",
        "One-command full flow script if you just want to run the whole thing",
        "Built to be repeatable, easy to drop into any mod workflow",
      ],
      tech: ["Batchfile", "Python", "apktool", "smali / baksmali", "uber-apk-signer"],
    },
  },
  {
    slug: "iyai",
    title: "IYAI",
    description: "Lua plugin for Infinite Yield that adds a full AI assistant. It can explore the game tree, run Lua, search the web, and fire IY commands, all from a chat UI.",
    tags: ["Lua", "AI", "Plugin"],
    link: "https://github.com/imluri/IYAI",
    webLink: "/iyai",
    image: "https://raw.githubusercontent.com/imluri/IYAI/main/logo.png",
    imageAlt: "IYAI Logo",
    details: {
      year: "2026",
      status: "Active",
      summary: "IYAI is a Lua plugin for the Infinite Yield Roblox admin script that wires in a full AI assistant. It can browse the instance tree, read and set properties, write and run Lua, search the web, and fire IY commands, all from a chat UI.",
      highlights: [
        "Full AI chat loop with tool calls, reasoning, and streamed responses",
        "Browse the Roblox instance tree and read/set properties on any object",
        "Write, edit, and execute Lua directly from the plugin",
        "Works with OpenRouter, Mistral, Groq, Google AI Studio, Pollinations, HuggingFace, and Ollama",
        "Live model picker that pulls available models from whichever provider you pick",
        "Rate-limit retry, inline error display, stop button, and full session history",
        "GUI parented to gethui so the game doesn't detect it",
        "Auto-updates on every run by pulling the latest version from GitHub",
      ],
      tech: ["Lua", "Roblox API", "OpenRouter", "Groq", "Google AI Studio", "DuckDuckGo Search"],
    },
  },
  {
    slug: "lami",
    title: "Lami",
    description: "AI chatbot I built using MCP architecture. Hooks into live data, automates tasks, and actually understands context across a conversation.",
    tags: ["Python", "Flask", "AI", "MCP"],
    link: "https://lami.up.railway.app/",
    image: "assets/lami-web.png",
    imageAlt: "Lami",
    fullscreen: true,
    details: {
      year: "2025",
      status: "Active",
      summary: "Lami is an AI chatbot built on MCP (Model Context Protocol). It pulls in live data, automates tasks on command, and keeps context across the whole conversation.",
      highlights: [
        "MCP architecture so the AI can actually act on things, not just talk about them",
        "Hooks into real-time data sources and runs analysis on the fly",
        "Natural language task automation, just tell it what to do",
        "Python/Flask backend with a clean responsive frontend",
        "Deployed on Railway with persistent session management",
      ],
      tech: ["Python", "Flask", "MCP", "NLP", "HTML/CSS", "Real-Time Data"],
    },
  },
  {
    slug: "sedapsnaps",
    title: "SedapSnaps",
    description: "Food discovery PWA with AI recommendations, full offline support, and push notifications. Scored 95 on Lighthouse and got 60% higher mobile engagement.",
    tags: ["PWA", "JavaScript", "AI"],
    link: "https://sedapsnaps.com",
    image: "assets/sedapsnaps.png",
    imageAlt: "SedapSnaps",
    fullscreen: true,
    details: {
      year: "2024",
      status: "Active",
      summary: "SedapSnaps is a food discovery PWA with AI recommendations. Works fully offline, sends push notifications, and scored 95 on Lighthouse with 60% higher mobile engagement.",
      highlights: [
        "AI recommendations that actually match what the user wants",
        "Full offline mode with service worker and local caching",
        "Push notifications for new food discoveries",
        "95 Lighthouse PWA score across performance, accessibility, and best practices",
        "60% higher mobile engagement over the baseline",
      ],
      tech: ["JavaScript", "PWA", "Service Workers", "Push API", "AI Recommendations"],
    },
  },
  {
    slug: "perekaperabot",
    title: "PerekaPerabot",
    description: "Full website for a Malaysian furniture and interior design company. Built the UI, database, AI chatbot assistant, and a 3D measurement tool.",
    tags: ["Python", "Supabase", "Gemini AI", "Tailwind"],
    link: "https://perekaperabot.com.my",
    image: "assets/perekaperabot.png",
    fullscreen: true,
    icon: "mdi:sofa-outline",
    details: {
      year: "2025",
      status: "Active",
      summary: "PerekaPerabot is a full website I built for a Malaysian furniture and space design company. Covers everything from the public-facing portfolio and gallery to a bilingual AI chatbot, user auth, and a 3D room measurement tool.",
      highlights: [
        "Bilingual AI chatbot (English and Malay) powered by Gemini with custom prompt engineering",
        "User authentication and account management backed by Supabase",
        "Portfolio and gallery sections showcasing the company's furniture and design projects",
        "3D measurement tool for spatial planning and room visualisation",
        "Multi-language support across the full site",
        "Integrated contact channels: WhatsApp, email, and social media links",
      ],
      tech: ["Python", "Supabase", "Gemini AI", "HTML", "Tailwind CSS"],
    },
  },
  {
    slug: "cibot",
    title: "AI Environmental Reporting Bot",
    description: "Chatbot where citizens can report environmental issues via chat, attach photos, and it generates a structured report for the relevant government department.",
    tags: ["Python", "NLP", "Image Analysis", "AI"],
    link: "https://cibot.my",
    image: "assets/cibot.png",
    imageAlt: "CiBot",
    fullscreen: true,
    details: {
      year: "2025",
      status: "Active",
      summary: "CiBot is an AI chatbot I built during my internship. Citizens can report potholes, flooding, illegal dumping, whatever, just send a message and a photo and it generates a proper incident report for the government.",
      highlights: [
        "Chat interface so anyone can report an issue without filling out a form",
        "Analyses attached images to figure out what's actually being reported",
        "Generates structured, government-ready incident reports automatically",
        "NLP intent classification routes each report to the right department",
        "Built and deployed during my AI Engineering internship",
      ],
      tech: ["Python", "NLP", "Image Analysis", "Report Generation", "Government Integration"],
    },
  },
];

const TOOLS = [
  {
    title: "Network Utilities",
    description: "Local scripts for testing connectivity, diagnosing network issues, and measuring performance.",
    tags: ["Networking", "Tools", "Diagnostics"],
    icon: "mdi:server-network",
    link: null,
  },
  {
    title: "Performance Tools",
    description: "Scripts for measuring latency and response time. Mostly built for checking if my changes actually made things faster.",
    tags: ["Performance", "Monitoring", "Analysis"],
    icon: "mdi:speedometer",
    link: null,
  },
  {
    title: "3D Experiments",
    description: "Playing around with interactive 3D in the browser. Mostly visual prototypes and rendering tests.",
    tags: ["3D", "Visualization", "Interactive"],
    icon: "mdi:cube-scan",
    link: null,
  },
  {
    title: "Game Prototypes",
    description: "Half-finished game ideas and browser experiments. Some get finished, most don't.",
    tags: ["Games", "Prototype", "Browser"],
    icon: "mdi:gamepad-square",
    link: null,
  },
];

const DESIGNS = [];

// Web design concepts — shown via iframe on the project detail page
const DESIGN_PROJECTS = [
  {
    slug: "nke",
    title: "Nasi Kandar Express",
    description: "Mamak restaurant website concept. Bright colours, bold type, warm layout. Built with plain HTML and CSS.",
    tags: ["UI/UX", "HTML", "CSS"],
    link: null,
    image: "https://raw.githubusercontent.com/imluri/imluri.github.io/main/assets/NKE_web.png",
    imageAlt: "Nasi Kandar Express preview",
    fullscreen: true,
    designSrc: "designs/NKE.html",
    details: {
      year: "2024",
      status: "Design",
      summary: "Concept website for a mamak restaurant chain. Bright colours, bold text, warm feel. Built with plain HTML and CSS.",
      highlights: [
        "Warm, high-contrast colours that fit the mamak vibe",
        "Bold hero section with a clear CTA",
        "Responsive layout in pure HTML and CSS",
        "Menu section with a card-based food display",
      ],
      tech: ["HTML", "CSS"],
    },
  },
  {
    slug: "browniemunch",
    title: "BROWNIEMUNCH",
    description: "Bakery website concept with warm chocolate tones, product showcase, and a cozy layout that makes you want to order something.",
    tags: ["UI/UX", "HTML", "CSS"],
    link: null,
    image: "https://raw.githubusercontent.com/imluri/imluri.github.io/main/assets/BROWNIEMUNCH_web.png",
    imageAlt: "BROWNIEMUNCH preview",
    fullscreen: true,
    designSrc: "designs/browniemunch.html",
    details: {
      year: "2024",
      status: "Design",
      summary: "Concept website for an artisanal brownie brand. Warm chocolate tones, cozy layout, the kind of site that makes you want to buy something.",
      highlights: [
        "Chocolate and cream colour scheme that fits the brand",
        "Product showcase grid with hover effects",
        "Typography that feels handmade without being hard to read",
        "Fully responsive across mobile and desktop",
      ],
      tech: ["HTML", "CSS"],
    },
  },
  {
    slug: "nexus",
    title: "Nexus.AI",
    description: "Dark sci-fi SaaS landing page concept. Glowing cyan accents, animated typewriter hero, and the kind of vibe that says 'we use AI for everything'.",
    tags: ["UI/UX", "HTML", "Tailwind"],
    link: null,
    image: null,
    icon: "mdi:web",
    imageAlt: "Nexus.AI preview",
    designSrc: "designs/nexus.html",
    details: {
      year: "2024",
      status: "Design",
      summary: "Dark sci-fi SaaS landing page concept for a fictional AI platform. Glowing cyan, animated typewriter hero, the full thing.",
      highlights: [
        "Animated typewriter effect in the hero",
        "Glowing cyan accents on a pure black background",
        "Glassmorphism feature cards with a subtle border glow",
        "Pricing section and CTA that feel intentional",
      ],
      tech: ["HTML", "Tailwind CSS"],
    },
  },
];

// Hobby projects — personal stuff outside work
const HOBBIES = [
  {
    title: "Unity Game Mods & Cheats",
    description: "C# mods for Unity games. Memory patching, internal hooks, overlays, automation. The kind of stuff you can't google.",
    tags: ["C#", "Unity", "Reverse Engineering"],
    icon: "mdi:sword-cross",
    link: null,
  },
  {
    title: "Game Development",
    description: "Personal Unity projects. Some are just mechanics experiments, a few actually got finished.",
    tags: ["C#", "Unity", "Game Dev"],
    icon: "mdi:controller-classic",
    link: null,
  },
  {
    title: "Roblox / Luau Scripting",
    description: "Games and tools built on Roblox. Multiplayer systems, admin scripts, random gameplay stuff.",
    tags: ["Luau", "Roblox", "Games"],
    icon: "mdi:gamepad-variant",
    link: null,
  },
];
